development: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:

development:
  <<: *default
  host: db

test:
  <<: *default
  host: db
