default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  host: postgres
  port: 5432


development:
  <<: *default
  host: postgres

test:
  <<: *default
  host: postgres
